### ISSUE TITLE
Update carrierwave dependency to allow version 0.11.2

### ISSUE THREAD

**Issue by guilleart** [carrierwaveuploader/carrierwave-mongoid#160] opened 2016-05-11 18:47 UTC
https://github.com/carrierwaveuploader/carrierwave/issues/1933

I tried updating carrierwave to 0.11.2 but Bundler resolved the dependency to use version 0.1.0 of carrierwave-mongoid which in turn broke the uploaders in my app (images are no longer visible).

**Comment by rmm5t** [comment] 2016-05-18 17:34
> We're not releasing an official version until we fully support the new features in carrierwave v0.11.0. Specifically `mount_uploaders`. I've been too busy to code this up myself, and no one else has been able to submit us a green pull-request yet, so help is appreciated here.

Closing as a dupe of #158, #156, #138 , #150, #157

In the meantime, use of the master branch is recommended.

**Closed by rmm5t** 2016-05-18 17:34 UTC

**Comment by rmm5t** [comment] 2016-06-13 13:58
Just a follow-up on this. The latest version of carrierwave-mongoid permits carrierwave 0.11 usage now.
